spring:
  application:
    name: mybatis

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # map-underscore-to-camel-case : ???? ???? ??? ??? ?????? ???? ?? ???? ?? ??
  mapper-locations: classpath:/mappers/**/*.xml
  # resources??(classpath:)???? mappers ???? ?? ?? ??(/**/)? ?? ?? .xml ??(*.xml)? ???.