spring:
  application:
    name: mybatis

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # map-underscore-to-camel-case : DB의 스네이크 케이스로 저장된 컬럼명을 카멜케이스로 매핑
  mapper-locations: classpath:/mappers/**/*.xml
  # resources 폴더를 가리키는(classpath:)의 mappers폴더 산하의 모든 하위 폴더의(/**/) 모든.xml(*.xml)